### ISSUE TITLE
Full info pop-up

### ISSUE THREAD

**Issue by SlyAceZeta** [SlyAceZeta/Ribbons.Guide#19] opened 2022-11-13 07:11 UTC
Add a pop-up that allows users to view a Pokémon's full details, functionally similar to their details in a main series game. This ties into #11.

**Comment by Azekthi** [comment] 2023-01-02 07:34
Functionality is already provided through edit form and ability to cancel that form.

**Comment by Azekthi** [comment] 2023-03-11 01:37
Duplicate of #55

**Closed by Azekthi** 2023-03-11 01:37 UTC
Labels: enhancement
